language: node_js
node_js:
  - "12.13.1"

jobs:
  include:
    - if: branch = dev
      install:
        - "npm ci"

      script:
        - "npm run build"
    - if: branch = master
      install:
        - "npm ci"
      script:
        - "npm run build"
      before_deploy:
        - which source
        - ls -l `which sh`
        - npm run release
        - export
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          target_branch: gh-pages
          local_dir: ./dist
          keep_history: true
          on:
            branch: master
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $PKG_VERSION.tar.gz
          prerelease: $PRE_RELEASE
          skip_cleanup: true
          on:
            branch: master
            condition: $RELEASE == true
