language: node_js
node_js:
  - "12.13.1"

jobs:
  include:
    - if: branch = dev
      install:
        - "npm ci"

      script:
        - "npm run build"
    - if: branch = master
      install:
        - "npm ci"
      script:
        - "npm run build"
      before_deploy:
        - tar -czvf $TRAVIS_TAG.tar.gz ./dist/*
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          target_branch: gh-pages
          local_dir: ./dist
          keep_history: true
          on:
            branch: master
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $TRAVIS_TAG.tar.gz
          skip_cleanup: true
          on:
            tags: true
