language: node_js
node_js:
  - "12.13.1"

jobs:
  include:
    - if: branch = dev
      install:
        - "npm ci"

      script:
        - "npm run build"
    - if: branch = master
      install:
        - "npm ci"
      script:
        - "npm run build"
      after_success:
        - "export PKG_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
        - git tag
        - git tag $PKG_VERSION
        - if [[ `git tag` =~ $PKG_VERSION ]]; then export RELEASE=true;tar -czvf $PKG_VERSION.tar.gz ./dist/*;echo $?;else echo $?;export RELEASE=flase;fi
        - if [[ $PKG_VERSION =~ \.0$ ]]; then export PRE_RELEASE=false;echo F;else export PRE_RELEASE=true;echo T;fi
        - git tag
        - export
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          target_branch: gh-pages
          local_dir: ./dist
          keep_history: true
          on:
            branch: master
        - provider: releases
          api_key: $GITHUB_TOKEN
          file: $PKG_VERSION.tar.gz
          prerelease: $PRE_RELEASE
          skip_cleanup: true
          on:
            branch: master
            condition: $RELEASE == true
